---
title: "dnSNV Genomic Regions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(ggplot2)
```


```{r load and format data}
DNM_df <- read.delim(here("../data", "dnSNVs_genomicRegion_intersection.bed"),
                     header = FALSE,
                     col.names = c("chrom","start","end","child","region"))

# table of counts by child and region; remove cases where region could not be assigned
plotting_table <- table(DNM_df$child, DNM_df$region)

plotting_table_df <- as.data.frame(plotting_table)
colnames(plotting_table_df) <- c("child","region","count")

plotting_table_df <- subset(plotting_table_df, region!=".")

```


```{r plot}
ggplot(plotting_table_df, aes(x=reorder(region, +count), y=count, fill=child))+
  geom_bar(stat="identity",position="dodge") +
  scale_fill_discrete(name="Child", breaks=c("proband","sibling"), labels=c("proband","sibling")) +
  scale_x_discrete(labels = c("5_UTR"="5'UTR", "3_UTR"="3'UTR", "CDS"= "Coding Sequence", "intron"="Intron", "intergenic"="Intergenic")) +
  theme_bw(base_size = 12) +
  theme(axis.title.x = element_text(margin = margin(t=6, r=0, b=0, l=0)), #space between axis labels and title
        axis.title.y = element_text(margin = margin(t=0, r=6, b=0, l=0))) +
  labs(
    x = "Genomic Region",
    y = "Number of de novo SNVs")# +
  #ylim(0,8000)
  #xlab("Genomic Region")+ylab("Number of de novo SNVs")
```

